services:
  db:
    image: postgres:15
    container_name: bi_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      TZ: Europe/Istanbul
    ports:
      - "5880:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bi-network

  app:
    build: .
    container_name: bi_app
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - bi-network

volumes:
  pgdata:

networks:
  bi-network:
    driver: bridge